### ISSUE TITLE
more possible plugins to include

### ISSUE THREAD

**Issue by snarfed** [indieweb/wordpress-indieweb#1]
thanks for the link, @pfefferle, i'd forgotten about this bundle. it's great!

here are a few more ideas for plugins to include, mostly taken from http://indiewebcamp.com/WordPress . i'd say SemPress too, but i don't know that a theme would fit well inside a plugin bundle. if it would, great!

- http://wordpress.org/plugins/indieauth-links/
- http://wordpress.org/plugins/indieauth/
- http://wordpress.org/plugins/relsyndication/
- https://github.com/pfefferle/wordpress-reply-context
- https://github.com/pfefferle/wordpress-uf2 (only if we don't include SemPress, and maybe disabled by default)

cc @jihaisse. feel free to close this issue, btw, it was just a place to start the conversation.

**Comment by dshanske** [comment]
Closing this for now. Added Indieauth and WordPresss Syndication. Moving WordPress-uf2 as a separate issue.
