### ISSUE TITLE
Consider Merging IndieAuth and Micropub into the Indieweb Plugin

### ISSUE THREAD

**Issue by dshanske** [indieweb/wordpress-indieweb#100]
This is a proposal made in chat. Opened this issue to discuss.

This would be merged as independent pieces within this plugin. A requirement would be that they be designed could be independently installed manually, but they would be developed and distributed together.

The rel-me piece would be adjusted in the same manner...moved into a subdirectory so that it could be easily installed by itself.

This would realign this back to the original 'Jetpack' module idea.

**Comment by dshanske** [comment]
For me, I can understand the pros and cons. It would reduce the development burden, as well as the burden for later generation individuals to install a variety of plugins.

**Comment by pfefferle** [comment]
I do not think the plugins are the main problem... I think the main problem is the theme support and the mf2 problem.

**Comment by aaronpk** [comment]
What problem is this solving? It sounds like from your comment that it is only solving a development workflow problem? It would be good to capture the reasoning.

**Comment by dshanske** [comment]
IndieAuth as a client is implemented in both, basically

**Comment by dshanske** [comment]
It's the continual consolidation argument

**Comment by pfefferle** [comment]
Do you still want to work on the single plugins? My case is, that I want to run the plugins independent from the IndieWeb plugin.

**Comment by pfefferle** [comment]
@aaronpk I would like to give the question back: I think the merge of all these plugins "is only solving a development workflow problem". I do not see an issue here and would prefer to focus on problems like an alternative to the `wp-uf2` plugin, or more concrete, the WordPress theme issues.

**Comment by pfefferle** [comment]
Sorry, perhaps the wrong place to discuss this, but I searched through the issues of we ever talked about themes and how we improve the handling of themes with only microformats1 or broken microformats support

**Comment by miklb** [comment]
the single most common piece of feedback from beginning users has and continues to be that there are too many plugins, folks don't know which plugins they should install.

If a better on boarding user experience the goal, then at some point merging plugins would be useful. But solving mf2 & theme issues is probably a higher priority in that area right now.

**Comment by dshanske** [comment]
Closing this.
