### ISSUE TITLE
Add Websub plugin

### ISSUE THREAD

**Issue by dshanske** [indieweb/wordpress-indieweb#104]
https://wordpress.org/plugins/pubsubhubbub/

Should the WebSub plugin be a recommended Indieweb plugin? 

@pfefferle As the developer, your thoughts?

**Comment by pfefferle** [comment]
Are there any IndieWeb usecases that support Websub? If so, sure, let's add it!

**Comment by dshanske** [comment]
All the new Indieweb readers.

**Comment by pfefferle** [comment]
Cool! Then sure, add it. Will try to implement a check if the theme supports microformats, to also send the HTML pages via WebSub.

**Comment by miklb** [comment]
This was addressed in #105 correct?

**Comment by dshanske** [comment]
Yes
