### ISSUE TITLE
H-Card User Widget - mismatched HTML open/close tags

### ISSUE THREAD

**Issue by cjwillcock** [indieweb/wordpress-indieweb#106]
The opened `<p>` is closed as `</h2>`

https://github.com/indieweb/wordpress-indieweb/blob/d5c3209d23626b59af715c225df8e959cb63c9b8/includes/class-hcard-user.php#L509

and

https://github.com/indieweb/wordpress-indieweb/blob/d5c3209d23626b59af715c225df8e959cb63c9b8/includes/class-hcard-user.php#L512

I'll try and figure out how to do a PR now.

**Comment by miklb** [comment]
Fixed in #107 props @cjwillcock
