### ISSUE TITLE
indieweb/wordpress-indieweb – PHP Notices

### ISSUE THREAD

**Issue by dougbeal** [indieweb/wordpress-indieweb#110]
`PHP Notice: Trying to get property 'ID' of non-object in /var/www/html/wp-content/plugins/indieweb/includes/class-hcard-user.php on line 445
PHP Notice: Trying to get property 'ID' of non-object in /var/www/html/wp-content/plugins/indieweb/includes/class-relme-widget.php on line 43`

[](https://github.com/indieweb/wordpress-indieweb/issues)

(Originally published at: https://crw.moe/b/ZS)

**Comment by tw2113** [comment]
@pfefferle do we think this has since been resolved? The original PR above isn't the current status, as I had made further edits afterwards to help address concerns.
