### ISSUE TITLE
Establish Criteria for Adding Custom Fields to User Profile

### ISSUE THREAD

**Issue by dshanske** [indieweb/wordpress-indieweb#121]
In #120 there was a request for adding a Mastodon profile field. This is partly because the auto domain matching wouldn't work for Mastodon because the instances are federated.

Mastodon supports rel-me for identity verification, so it has a functional place in a rel-me widget. 

I'm not a Mastodon user. I'd have to look and see where Mastodon plugins for WordPress generally store their mastodon urls in the user profile(hopefully in a field called mastodon) to try to avoid duplication. 

I'm personally neutral on this. My only concern is that we can't custom code for every service, and what the criteria is for having a custom field vs the generic 'other profiles' option.

Originally, the criteria I used was:
* Supported by IndieAuth.com
* Supported by Brid.gy

Mastodon adds this third option
* Supports/uses rel-me.

So, is there anything else? This is a bit into the weeds, but I'd like to sort of say what does and does not belong here in the long run.

**Comment by bekoli** [comment]
I use [Mastodon Auto Post](https://github.com/simonfrey/mastodon_wordpress_autopost)

It stores the instance variable in `option_name` as `autopostToMastodon-instance`. Example: `http://social.tchncs.de` (tho it does display https in settings dialog). The ID is not stored, just the token. Mayhap that's enough to match when added as `Other Sites` to rel=me?

Syndication Links seems to work just fine with Mastodon as of Version 3.4.0 ( 2018-03-03 ):
```
* Added support for Mastodon Auto Post per request. Unable to test due not using same
```
Site with Syndication Links looks like this:
![image](https://user-images.githubusercontent.com/5016428/63800381-46704a00-c90e-11e9-9f7b-2be608993def.png)

**Comment by dshanske** [comment]
Closing this in favor of #122
