### ISSUE TITLE
Call to undefined method HCard_User::get_me_list()

### ISSUE THREAD

**Issue by cjwillcock** [indieweb/wordpress-indieweb#127]
The most recent commit has a call to get_me_list() which should be get_rel_me_list() on line 402 of includes/class-hcard-user.php.

Including the HCard widget in sidebar gives the error: 

> Fatal error: Uncaught Error: Call to undefined method HCard_User::get_me_list() in /home/indiesee/public_html/wp-content/plugins/indieweb/includes/class-hcard-user.php:402 ...

**Comment by dshanske** [comment]
I tested it I thought

**Comment by dshanske** [comment]
I will issue a fix this evening.

**Comment by pauljacobson** [comment]
I seem to have been affected by the same issue. It caused a `500 Internal Server error` on my site <https://pauljacobson.me>. Here's the error message from my logs:

```
PHP Fatal error: Uncaught Error: Call to undefined method HCard_User::get_me_list() in /pljcbsn/wp-content/plugins/indieweb/includes/class-hcard-user.php:402 Stack trace: #0 /pljcbsn/wp-content/plugins/indieweb/includes/class-relme-widget.php(53): HCard_User::rel_me_list(1, true) #1 /wordpress/core/4.9.8/wp-includes/class-wp-widget.php(372): RelMe_Widget->widget(Array, Array) #2 /wordpress/core/4.9.8/wp-includes/widgets.php(743): WP_Widget->display_callback(Array, Array) #3 /pljcbsn/wp-content/themes/independent-publisher-2-wpcom/footer.php(20): dynamic_sidebar('sidebar-2') #4 /wordpress/core/4.9.8/wp-includes/template.php(688): require_once('/pljcbsn/wp-con...') #5 /wordpress/core/4.9.8/wp-includes/template.php(647): load_template('/pljcbsn/wp-con...', true) #6 /wordpress/core/4.9.8/wp-includes/general-template.php(76): locate_template(Array, true) #7 /pljcbsn/wp-content/themes/independent-publisher-2-wpcom/index.php(54): get_footer() #8 /wordpress/core/4.9.8/wp-includes/template-loader.php
```

My site upgraded to v3.3.12 yesterday (3 December), and I noticed this issue this morning. My site is running WordPress 4.9.8. I also opened an issue in the plugin support page, here: [Topic: 500 Internal Server error for version 3.3.12 | WordPress.org](https://wordpress.org/support/topic/500-internal-server-error-for-version-3-3-12/)

**Comment by dshanske** [comment]
Just pushed the fix. Apologies for the inconvenience. Should be in the .org repo in a few.

**Comment by pauljacobson** [comment]
Thank you for fixing this so quickly!

**Comment by pauljacobson** [comment]
These things happen, I'm just glad it's been resolved. My blog was feeling very disconnected with the plugin disabled.
