### ISSUE TITLE
Remove Facebook field

### ISSUE THREAD

**Issue by dshanske** [indieweb/wordpress-indieweb#154]
As Facebook is no longer supported in any Indieweb product... proposing the field be removed. It can still be added in the other rel me links section.

**Comment by tw2113** [comment]
I support the idea, but do wonder how many people would still want the field and are maybe using it somehow.

Perhaps there would be benefit to provide a snippet of code to re-add the one field, that could be shared in support requests if they come up.

That said, the data wouldn't be gone just the UI to edit afterwards.

**Comment by dshanske** [comment]
The original criteria for adding was works with Indieweb or supports rel me

**Comment by tw2113** [comment]
Still wouldn't hurt for a quick snippet to re-add if someone somehow really needed to add the UI back in, on their own.

**Comment by dshanske** [comment]
Closing this as Bridgy now limitedly supports Facebook again
