### ISSUE TITLE
Double icons for mastodon

### ISSUE THREAD

**Issue by metbril** [indieweb/wordpress-indieweb#164]
When entering a Mastodon URL, multiple icons are shown.

Reproduce: enter `https://mastodon.social/@metbril` or `https://mastodon.social/@metbril` or `https://mastodon.xyz/@metbril` or `https://example.org/@metbril` wil show:

<img width="126" alt="Schermafbeelding 2021-03-01 om 21 18 58" src="https://user-images.githubusercontent.com/559346/109553881-d7ac1800-7ad3-11eb-8169-8c1b1c9fc096.png">

The first icon (with the three dots) is shown by the "before" style:

<img width="457" alt="Schermafbeelding 2021-03-01 om 21 24 26" src="https://user-images.githubusercontent.com/559346/109554503-9831fb80-7ad4-11eb-92c8-b0e49ff13080.png">

The second icon (with the "M") is shown by the span:

<img width="476" alt="Schermafbeelding 2021-03-01 om 21 24 47" src="https://user-images.githubusercontent.com/559346/109554615-bd266e80-7ad4-11eb-9641-2f053ade9fe5.png">

**Comment by pfefferle** [comment]
This is an issue of SemPress... I will fix it there! Thanks for reporting!

**Comment by pfefferle** [comment]
oh, it is Autonomie, not SemPress

**Comment by pfefferle** [comment]
Fixed https://github.com/pfefferle/autonomie/commit/a947515806f1d7d0983d711d3b778f3961c1c1cb
