### ISSUE TITLE
Remove Syndication Links from the recommended plugins?

### ISSUE THREAD

**Issue by killerog** [indieweb/wordpress-indieweb#19]
Hey,

Both Syndication Links and rel-syndication are mentioned in the recommended links, while they do pretty much the same as far as it looks. Only Syndication Links doesn't add the rel="syndication" to the link which is a should have according to the wiki: http://microformats.org/wiki/rel-syndication
So it might just be as well to remove this to prevent plugin overload? I could probably create a pull request if you'd like that.

Thanks!

**Comment by pfefferle** [comment]
I am not sure about both plugins, because I am not using them... Perhaps @dshanske knows the difference...

**Comment by dshanske** [comment]
killerog is incorrect. Syndicaton Links adds the rel="syndication" only on single pages. It adds "u-syndication" on archive pages. It is doing so correctly.

I think Syndication Links is the better plugin because it has more features and is more flexible. Of course, I wrote it, so I'm a bit biased.
