### ISSUE TITLE
Better Integrate Indieweb Plugins by Consolidating Settings for All Plugins 

### ISSUE THREAD

**Issue by dshanske** [indieweb/wordpress-indieweb#22]
This was suggested in the Indieweb IRC chat. If we have a top level element created by the Indieweb plugin, and in the event that class Indiewebplugin exists, then move the settings pages to this Indieweb Top Level Menu item, and maybe add some additional context and guidance.

**Comment by pfefferle** [comment]
:+1:

**Comment by dshanske** [comment]
Menu is in latest version. Already added code to Syndication Links and Post Kinds that it will automatically move the menu if the Indieweb Plugin is enabled.
