### ISSUE TITLE
Indiemark Level 1

### ISSUE THREAD

**Issue by dshanske** [indieweb/wordpress-indieweb#23]
There was some discussion. Proposing rel me functionality be added to the plugin. That would allow newcomers to achieve the first Indiemark Level merely by installing the plugin.

**Comment by dshanske** [comment]
Proposed functionality would add user meta fields to user profile, identify single vs multi author sites, and address rel me and some basic hcard functionality.

**Comment by pfefferle** [comment]
@singpolyma wrote an extended-profile plugin long time ago. I think it implements most of the feature you might thought about. Perhaps we can reuse some of its features, or maybe @singpolyma gives us access so we could update the plugin to microformats v2: https://wordpress.org/plugins/extended-profile/

**Comment by singpolyma** [comment]
I've pulled out the code from the deprecated diso repo and posted here: https://github.com/singpolyma/wordpress-extended-profile

I still run this plugin on my site, so it should work.

Pull requests welcome.  I'll accept mf2 markup, but please don't remove the real microformats classes already present :)

**Comment by dshanske** [comment]
@petermolnar has written in a basic implementation. I'm going to at some point take what I did with rel-me in Syndication Links and merge it into the effort, as well as look at WordPress Extended Profile and see what we can add from there.
