### ISSUE TITLE
Since latest update "No webmention support"

### ISSUE THREAD

**Issue by cybeardjm** [indieweb/wordpress-indieweb#255]
Just updated to 4.0.3
Since then, when checking on likes/boosts on Mastodon via Bridgy, all posts/interactions are marked as "no webmention support".
If I check via Webmention on my WordPress blog, I get the full JSON...
Tried disabling/enabling both IndieWeb and Webmention plugins, nothing happens.

**Comment by dshanske** [comment]
I'm not sure how those two things would be related. The changes in 4.0.3 were about adding a Bluesky profile field.

@snarfed Can you assist?

**Comment by cybeardjm** [comment]
@dshanske @snarfed OK, after restarting everything (including server), it's back... Closing.
