### ISSUE TITLE
Limit rel-me links to author pages and maybe front page

### ISSUE THREAD

**Issue by voxpelli** [indieweb/wordpress-indieweb#26]
As a follow up to #24 by @petermolnar and after discussions on IRC both [this morning](http://indiewebcamp.com/irc/2016-01-26#t1453806787871) and this afternoon about where to add or not to add `rel-me` links I wanted to add this issue.

The `rel-me` relations in the widget added in the referenced PR should as I see it only be added on the profile pages that represents the same user as the linked to links, not on all pages as is the case now.

This can be achieved in one of two ways:

1. Either only show the widget on profile pages (and maybe front page)
2. Or always show the widget but only add the `rel-me` relation to those links when the widget is shown on a profile page (or maybe front page)

After [discussions with](http://indiewebcamp.com/irc/2016-01-26/line/1453830408966) @tantek I added a question and answer to the IndieWebCamp wiki on this issue: https://indiewebcamp.com/rel-me#Can_I_add_rel-me_to_non-profile_pages.3F Although @tantek [also pointed out](http://indiewebcamp.com/irc/2016-01-26/line/1453831544940) that others such as @aaronpk might not agree with that answer.

Still: I think using `rel-me` on anything but profile pages is harmful and eg. makes it very hard to [consolidate](http://microformats.org/wiki/identity-consolidation) any identities within an indieweb [social graph](https://indiewebcamp.com/social_graph).

Sometimes it's useful to replace `rel-me` with `rel-author` instead, but not in this case I would say – for two reasons:

1. WordPress supports `rel-author` out of the box and links to profile pages already so as long as the `rel-me` links can be found on them then they can be found. Eg. https://indiewebcamp.com/authorship describes that flow.
2. Multiple `rel-author` links on the same page means multiple authors, not multiple other profiles for the same author, so it will give an incorrect impression that can only be corrected by fully consolidating the identity of the linked to profiles.

So – all in all: I think `rel-me` should be removed through one of the initially outlined ways.

**Comment by dshanske** [comment]
This was one of my concerns. I want to add some logic to this using the is_multi author conditional to help decide where the tags should be

**Comment by petermolnar** [comment]
I only added a widget. How and where the widget is shown is up to the theme in use.

On 26 January 2016 18:32:35 GMT+00:00, David Shanske <notifications@github.com> wrote:
>This was one of my concerns. I want to add some logic to this using the
>is_multi author conditional to help decide where the tags should be 
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/indieweb/wordpress-indieweb/issues/26#issuecomment-175162526

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by voxpelli** [comment]
@petermolnar Please correct me if I'm wrong, but the themes that ship with WordPress by default show all widgets on all pages? Only advanced themes and custom themes have specific widget regions that are only shown on certain pages such as the profile page or other similar mechanisms to show and hide widgets on a subset of pages, right?

I also think that the better solution is probably to make the `rel-me` relation only be added on the profile page and the front page rather than hiding the entire widget and that is something that only the widget can do I believe?

@dshanske yeah, a combination of `is_multi_author()`, `is_author()` and `is_front_page()` would probably do the trick
