### ISSUE TITLE
H-Card Enhancements

### ISSUE THREAD

**Issue by dshanske** [indieweb/wordpress-indieweb#30]
There was some question in IRC as to whether I was going too far, and if some of this shouldn't be in another plugin. I thought I'd lay out what I'm working on for feedback.

Like the Rel-Me enhancements, this is based on the multi-author vs single author issue. I want to add a simple h-card generating function that can be embedded in an arbitrary page by use of a shortcode. For a multi-author site, this would allow that page to be the representative h-card on the site if needed. For a single author site, that page could optionally be set to the homepage.

That would allow anyone to get a simple Indieweb site up and running quickly with it establishing their identity for other Indieweb sites.

**Comment by miklb** [comment]
Was this addressed in 523ee4cce59b4c397391ce7f0250e9fa5f155e23

**Comment by dshanske** [comment]
The first part was yes. But no shortcode yet.

**Comment by dshanske** [comment]
Related #109

**Comment by dixonge** [comment]
FYI, my site is failing validation on Indiewebify.me due to not having a 'representative h-card' when fed my main root URL:

https://indiewebify.me/validate-h-card/?url=https%3A%2F%2Fglenn.thedixons.net

it's asking that I add a 'u-url' to match a 'rel=me' on the page.

**Comment by dshanske** [comment]
We discovered a trailing slash can create an issue.

**Comment by gRegorLove** [comment]
@dixonge That's actually a bug with indiewebify.me that I should have fixed soon. Your homepage representative h-card is all good! The indiewebify.me issue is: https://github.com/indieweb/indiewebify-me/issues/75
