### ISSUE TITLE
Missing Titles

### ISSUE THREAD

**Issue by mrkrndvs** [indieweb/wordpress-indieweb#33]
I did read that IndieWeb may not play nicely with all themes. However, it was removing the title from my posts. I have deactivated all the plugins and updated and the title is back. Have I done something wrong? I also noticed that the shortener was producing a 440 message for some reason. In case you are wondering, I am running WordPress 4.5.2 running Storto theme.

**Comment by dshanske** [comment]
Can you narrow it down to the specific plugin that is causing this and file the report there?

It is possible that it is Post Kinds, which does remove the title when it isn't an article post. But there was a complaint about that behavior that is pending in the next version.

**Comment by mrkrndvs** [comment]
Yes David, just did some more testing. It is Post Kinds. I will disable for now then and what for an update. Thank you.
