### ISSUE TITLE
Better description in readme

### ISSUE THREAD

**Issue by pfefferle** [indieweb/wordpress-indieweb#34]
The plugin and the IndieWeb idea is not self describing and might be a bit complicated for newbies, so we should add a more descriptive text to the readme: https://wordpress.org/support/topic/might-be-helpful-to-add-at-least-some-description

**Comment by dshanske** [comment]
Seemed resolved, but a continual struggle.

**Comment by chrisaldrich** [comment]
I've got this on my general to do list and will try to revisit it at regular 4 month intervals to help us all keep abreast...
