### ISSUE TITLE
Cannot redeclare class RelMe_Widget

### ISSUE THREAD

**Issue by chrisaldrich** [indieweb/wordpress-indieweb#36]
Just updated to the newest IndieWeb plugin and got:
Fatal error: Cannot redeclare class RelMe_Widget in /wp-content/plugins/indieweb/includes/class-relme-widget.php on line 87

I hadn't gotten a chance to do the update to Syndication Links yet. Could that be related? Do they both need to be updated simultaneously?

**Comment by dshanske** [comment]
They do. It removed the widget from one and moves it into the other.

**Comment by chrisaldrich** [comment]
<a href="https://github.com/indieweb/wordpress-indieweb/issues/36" class="u-in-reply-to"></a>Thanks!

Like the move of the plugin into the main menu and what a great icon for it!
