### ISSUE TITLE
IndieWeb Comments

### ISSUE THREAD

**Issue by mrkrndvs** [indieweb/wordpress-indieweb#38]
I have installed the IndieWeb plugins, but have found that all of the comments coming from Twitter, Google+ etc are automatically sent to the spam by Akismet. Does anyone have any thoughts or suggestions?

**Comment by armingrewe** [comment]
I've noticed similar, although over time Akismet at least partially learned. It also seems to fluctuate, sometimes it sends everything to spam, sometimes almost everything comes through.

There is a way to get them pre-approved which someone posted somewhere (either here or on @snarfed 's bridgy group), unfortunately I can't remember/find it just now. To do that you would have to add some code (which for a reason I can't remember I haven't done yet)

**Comment by dshanske** [comment]
I wrote some code to whitelist specific domains. Let me see if I can get something out.

**Comment by armingrewe** [comment]
While (unsuccessfully) trying to find it, I vaguely remember someone posting code you could add to get any webmention through from people who previously had a webmention approved. Basically similar to the function for a normal comment where people with a previous comment are automatically approved. Thinking about it, this might have been in relation to the fact that currently any webmention needs approval, regardless if there have been previous approved webmentions from the same author.

For some reason I can't find that discussion any more, if anyone can point me in the right direction I would appreciate it.

**Comment by snarfed** [comment]
here's the code i use in `functions.php.txt` to always approve webmentions:

```
function unspam_webmentions($approved, $commentdata) {
  return $commentdata['comment_type'] == 'webmention' ? 1 : $approved;
}
add_filter('pre_comment_approved', 'unspam_webmentions', '99', 2);
```

**Comment by dshanske** [comment]
There is a filter in webmentions to approve all webmentions. However, if they become more popular, they will be a target for spam, and that isn't a long term solution. Will keep this open and report back with some efforts. I see Akismet recommends you talk to them about custom comment types. Going to give that a shot.

**Comment by dshanske** [comment]
I emailed Akismet. They asked for API keys of the individuals having the problem so they could look at the data. Anyone want to drop them a line?

**Comment by armingrewe** [comment]
As mentioned in my case it fluctuates, sometimes a lot gets marked as spam, at other times everything passes just fine.
Would be happy to let them look at my data, what reference/email address?

**Comment by dshanske** [comment]
support@akismet.com, put [#2699153] at the beginning of the subject line as the case reference.

**Comment by armingrewe** [comment]
OK, will do tonight when I'm back home, on the phone just now.

**Comment by chrisaldrich** [comment]
<a href="https://github.com/indieweb/wordpress-indieweb/issues/38" class="u-in-reply-to"></a>I've dropped them a note to the referenced number as well.  Thanks @dshanske!

**Comment by dshanske** [comment]
For now, since this is a webmentions/semantic linkbacks issue, not embedded in the code in this plugin, will close the issue. Spam and moderation continues to be a discussion on the individual pieces.
