### ISSUE TITLE
WordPress coding standard

### ISSUE THREAD

**Issue by pfefferle** [indieweb/wordpress-indieweb#41]
There are a lot of coding standard issues mainly in the classes of the includes folder.

**Comment by dshanske** [comment]
Fixed four strict comparison errors, and it now runs through the included phpcs file.

**Comment by dshanske** [comment]
However, if you change the parameters to the standard WordPress codesniffer, there are several more which could be fixed in terms of validation. Would suggest we decide on the parameters being checked.

**Comment by pfefferle** [comment]
You can't fully rely on checkers and plugins, because they don't find any "problem": https://github.com/indieweb/wordpress-indieweb/commit/5d1efeb76a8333adbe51c626d54e47a67b676905
