### ISSUE TITLE
After plugin activation, no link elements show up in head

### ISSUE THREAD

**Issue by asuh** [indieweb/wordpress-indieweb#51]
I've tested this on more than one site where I do not see any new link elements showing up in the head of the source code with links to any of the social accounts in the main profile. I checked the IndieWeb Options section to make sure the default author is correct and exists and it was fine.

When I use the `Rel=Me` widget, only then do I see the social links in the widget I've added it to. When I delete it from a widget section, there are no link elements in the head.

**Comment by dshanske** [comment]
You inspired me to rearrange my plans and work on a new release for WordPress.org that addresses this and other things. Thanks.

**Comment by dshanske** [comment]
Addressed in PR #52

**Comment by asuh** [comment]
I initially did a git clone of this when it was version 3.0.7 but ran an auto-update in the Dashboard which brought it to 3.1.0. 3.0.7 fixed the missing link elements in the head but now version 3.1.0 is showing the same issues as <3.0.7.

**Comment by dshanske** [comment]
I tested it before I deployed it. Odd.

**Comment by pfefferle** [comment]
have you hit the save button on the single user settings?

**Comment by asuh** [comment]
I went to the Options section and hit the save button. Same result on 2 different sites.

**Comment by pfefferle** [comment]
can you please post you links here, so that we can have a look?

**Comment by asuh** [comment]
I don't mind creating an account in my personal blog if you want to see the settings in the Dashboard. You can then see first hand. You'll learn nothing by viewing the source.

https://www.asuh.com

**Comment by dshanske** [comment]
I can't reproduce this.

**Comment by asuh** [comment]
I tried another domain and get the same result.

Maybe I'm just not understanding something about the [getting started on WordPress page](https://indieweb.org/Getting_Started_on_WordPress). Here's my process:

1. On existing WordPress site, install new Indieweb plugin
2. Activate Indieweb plugin
3. Verify default author is correct on `/admin.php?page=iw_general_options`
4. Go to profile of default author and add bare minimum of website and twitter username then save
5. Go to homepage and verify that `rel="me"` link element exists in `<head>`

I assume this is the bare minimum of what needs to be done just to make the rel=me link in the `<head>`. Did I leave anything out?

**Comment by asuh** [comment]
After playing around with `class-hcard-user.php`, I've determined that something that changed [since this version of the file has broken the link element](https://github.com/indieweb/wordpress-indieweb/commit/4bf682f56d5fcd9694767798e0b495a6dedf4b7d#diff-62eb6c22020a9e255e9e148477fc6c42) from showing.

I believe the fix has something to do with the default value of `get_option()` being true or false. If I add back in a string of `'1'` to both lines 413 and 414, that fixes the issue and `<link rel="me"...>` shows back up in the `<head>`.

**Comment by asuh** [comment]
I added pull request to show what fixed the issue for me.
https://github.com/indieweb/wordpress-indieweb/pull/55

**Comment by dshanske** [comment]
Try the latest version, which moves the registration, which was only fired in the admin...which appears to have been the problem. Advise and we'll close this.

**Comment by asuh** [comment]
Yes, I confirm this change fixed the issue.
