### ISSUE TITLE
Change menu icon

### ISSUE THREAD

**Issue by pfefferle** [indieweb/wordpress-indieweb#62]
We should change the menu icon... I do not think that there is a direct connection between the OpenShare icon and the IndieWeb...

**Comment by miklb** [comment]
I just [opened an issue](https://github.com/indieweb/branding/issues/13) in the branding repo to see about getting a square version of the IW logo, which could be used for a menu icon. It could probably help for the plugin icons too, especially the square icons for plugins in the WP admin page.

**Comment by dshanske** [comment]
I just used a built in icon. I would prefer the Indieweb logo.

**Comment by pfefferle** [comment]
is this something official?

**Comment by miklb** [comment]
Something  shaners was working on with @aaronpk is all I know.
