### ISSUE TITLE
Something is going wrong with time stamps when endpoint is WordPress 

### ISSUE THREAD

**Issue by dougbeal** [indieweb/wordpress-indieweb#73]
aaronpk/OwnYourSwarm#27

> :sigh: timezones. Looks like Wordpress is converting this and displaying it in UTC rather than in the local timezone. I'm not sure where in the Wordpress flow that's happening, but OwnYourSwarm sends the timestamp in the local time with the timezone offset. (2017-06-23T18:51:46-07:00)

**Comment by dshanske** [comment]
Fixed in development version of Micropub. Try again.
