### ISSUE TITLE
Other Sites Saves all URLs on One Line

### ISSUE THREAD

**Issue by miklb** [indieweb/wordpress-indieweb#76]
Users -> Your Profile -> Other Sites

Add 3 different URLs one on each line.

Save profile. All 3 URLs saves to same line.

Was reported in micro.blog WordPress channel that is preventing a micro.blog from verifying site.

Is this expected behavior?

**Comment by dshanske** [comment]
It shouldn't be. I had a similar design in Syndication Links, and switched it to an array. Probably should do the same here.
