### ISSUE TITLE
Comments Not Showing

### ISSUE THREAD

**Issue by RossGoodman** [indieweb/wordpress-indieweb#83]
I'm having an issue with my wordpress site where external comments are not showing.
They are being registered e.g. it says "2 thoughts on ..." but does not show the actual comments.

An example cam be seen here : https://www.rossgoodman.com/2017/10/15/falls-off-clyde/

**Comment by dshanske** [comment]
From the looks of it, you are using a WordPress comment replacement such as Disqus or Jetpack. This would hide the display.There are options, however.

**Comment by dshanske** [comment]
You can manually insert some code into your theme.

**Comment by RossGoodman** [comment]
Yes, I'm using Jetpack.
What code would I need to insert to make this work again?

**Comment by dshanske** [comment]
We have an issue filed with Jetpack. It takes over and disables anything in the hook we use. For now, go into Settings->Discussion and turn off the Facepile option. It will revert back to the older configuration.

**Comment by RossGoodman** [comment]
Thanks - I can now wee my comments!
They are bright yellow though :(

**Comment by dshanske** [comment]
Bright yellow? Nothing in the code should do that.

**Comment by RossGoodman** [comment]
https://www.rossgoodman.com/2017/10/21/2745/#comments
I know - I'll need to keep digging to get to the bottom of it.

Thanks for your help.

**Comment by chrisaldrich** [comment]
<a href="https://github.com/indieweb/wordpress-indieweb/issues/83#issuecomment-338246944" class="u-in-reply-to"></a>@RossGoodman are you by chance using a fragmentions plugin? If you are, the /#comments hash at the end of the URL will cause the targeted element to be highlighted in yellow like that.

**Comment by RossGoodman** [comment]
Yes I am - I disabled the plugin and the yellow is gone - thanks for that.

I think I need to review the plugins that I'm _actually_ using!

Thanks!!!
