### ISSUE TITLE
Icons for email and telephone

### ISSUE THREAD

**Issue by miklb** [indieweb/wordpress-indieweb#89]
Currently in the rel-me links for an h-card or maybe its the rel-me widget, the icon for email and phone are the generic icon (not sure what to call the three dots with lines).

I'm assuming the new icon set has a phone and email icon, so will just need to map the correct one?

**Comment by dshanske** [comment]
I will be redoing the icons and including a telephone and email icon. I also will add proper icons for other schemes per @tantek's contact brainstorming of a while back, like skype:

**Comment by dshanske** [comment]
Fixed in most recent merge.
