### ISSUE TITLE
Do not translate social network list

### ISSUE THREAD

**Issue by pfefferle** [indieweb/wordpress-indieweb#97]
The names of the social networks do not change for different languages.

We have nearly 500 different text-parts that needs to be tranlslated and that makes it really hard to do so: https://translate.wordpress.org/projects/wp-plugins/indieweb/dev/de/formal

**Comment by dshanske** [comment]
This is easily fixed as the file in question is autogenerated.

**Comment by dshanske** [comment]
Resolved via #99
