### ISSUE TITLE
Add Micro.blog to User Profile

### ISSUE THREAD

**Issue by dshanske** [indieweb/wordpress-indieweb#98]
Many people are signing up for micro.blog accounts, and it checks rel=me. We can help by supporting this field in the user profile.

**Comment by miklb** [comment]
So this is a UX decision to create a dedicated Micro.blog field in the profile settings vs the existing generic URL textbox which can not be moved to the upper section of the WordPress user page.

**Comment by dshanske** [comment]
Yes, based on observation of new users.

**Comment by dshanske** [comment]
Resolved via #99
